### ISSUE TITLE
tensorflow.contrib not found

### ISSUE THREAD

**Issue by haltosan** [FrancescoSaverioZuppichini/LSTM-Text-Generator#3]
Here's the error I got
`
$ python3 main.py --generate=True --from_model='shakespeare' --n_text=1000 --start_text="SIR " --layers=512,512
2021-07-06 20:02:07.318994: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-07-06 20:02:07.319032: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from model.train import train_model
  File "/home/kali/LSTM-Text-Generator/core/model/train.py", line 4, in <module>
    from model import model
  File "/home/kali/LSTM-Text-Generator/core/model/model.py", line 3, in <module>
    from tensorflow.contrib import rnn
ModuleNotFoundError: No module named 'tensorflow.contrib'
`
I just pip installed tensorflow about a minute before running this project. I'm not sure if it's my end or yours, but I would love it if you looked into this.

**Comment by MarsSpaceGo** [comment]
me too.
